# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\greub\OneDrive\Desktop\Computing VSC\pyocrgui\PY_OCR_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PY_OCR(object):
    def setupUi(self, PY_OCR):
        PY_OCR.setObjectName("PY_OCR")
        PY_OCR.resize(800, 626)
        self.centralwidget = QtWidgets.QWidget(PY_OCR)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 391, 241))
        self.label.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"border-color: rgb(100, 0, 0);\n"
"alternate-background-color: rgb(247, 247, 247);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 280, 181, 41))
        self.pushButton.setStyleSheet("background-color: rgb(254, 47, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 280, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 10, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 340, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(450, 30, 331, 531))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 360, 391, 241))
        self.label_2.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"border-color: rgb(100, 0, 0);\n"
"alternate-background-color: rgb(247, 247, 247);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 570, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        PY_OCR.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PY_OCR)
        self.statusbar.setObjectName("statusbar")
        PY_OCR.setStatusBar(self.statusbar)

        self.retranslateUi(PY_OCR)
        QtCore.QMetaObject.connectSlotsByName(PY_OCR)

    def retranslateUi(self, PY_OCR):
        _translate = QtCore.QCoreApplication.translate
        PY_OCR.setWindowTitle(_translate("PY_OCR", "PY_OCR"))
        self.pushButton.setText(_translate("PY_OCR", "EXTRACT"))
        self.pushButton_2.setText(_translate("PY_OCR", "Browse"))
        self.label_3.setText(_translate("PY_OCR", "Input Image"))
        self.label_4.setText(_translate("PY_OCR", "Output Image "))
        self.label_5.setText(_translate("PY_OCR", "Output Text "))
        self.pushButton_4.setText(_translate("PY_OCR", "Save to TXT"))


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_PY_OCR()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
        